from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ANNOUNCEMENT = Button(area={'cn': (631, 111, 675, 152)}, color={'cn': (48, 143, 231)}, button={'cn': (631, 111, 675, 152)}, file={'cn': './assets/cn/handler/ANNOUNCEMENT.png'})
ANNOUNCEMENT_CHECK = Button(area={'cn': (318, 264, 344, 297)}, color={'cn': (155, 197, 245)}, button={'cn': (318, 264, 344, 297)}, file={'cn': './assets/cn/handler/ANNOUNCEMENT_CHECK.png'})
AUTO_CLICK_CHECK = Button(area={'cn': (359, 22, 423, 41)}, color={'cn': (125, 125, 125)}, button={'cn': (359, 22, 423, 41)}, file={'cn': './assets/cn/handler/AUTO_CLICK_CHECK.png'})
CONFRIM_A = Button(area={'cn': (354, 819, 393, 844)}, color={'cn': (136, 217, 255)}, button={'cn': (354, 819, 393, 844)}, file={'cn': './assets/cn/handler/CONFRIM_A.png'})
CONFRIM_B = Button(area={'cn': (507, 790, 555, 813)}, color={'cn': (110, 197, 241)}, button={'cn': (507, 790, 555, 813)}, file={'cn': './assets/cn/handler/CONFRIM_B.png'})
CONFRIM_C = Button(area={'cn': (334, 1012, 385, 1036)}, color={'cn': (115, 206, 248)}, button={'cn': (334, 1012, 385, 1036)}, file={'cn': './assets/cn/handler/CONFRIM_C.png'})
DAILY_LOGIN_REWARD = Button(area={'cn': (77, 579, 109, 619)}, color={'cn': (206, 189, 108)}, button={'cn': (77, 579, 109, 619)}, file={'cn': './assets/cn/handler/DAILY_LOGIN_REWARD.png'})
DOWNLOAD_CHECK = Button(area={'cn': (115, 618, 356, 639)}, color={'cn': (201, 197, 201)}, button={'cn': (115, 618, 356, 639)}, file={'cn': './assets/cn/handler/DOWNLOAD_CHECK.png'})
LEVEL_UP_CHECK = Button(area={'cn': (312, 601, 408, 618)}, color={'cn': (0, 68, 129)}, button={'cn': (312, 601, 408, 618)}, file={'cn': './assets/cn/handler/LEVEL_UP_CHECK.png'})
LOGIN_CHECK = Button(area={'cn': (225, 1047, 496, 1068)}, color={'cn': (58, 58, 57)}, button={'cn': (225, 1047, 496, 1068)}, file={'cn': './assets/cn/handler/LOGIN_CHECK.png'})
LOGIN_PAGE_CHECK = Button(area={'cn': (229, 1247, 495, 1259)}, color={'cn': (64, 64, 63)}, button={'cn': (229, 1247, 495, 1259)}, file={'cn': './assets/cn/handler/LOGIN_PAGE_CHECK.png'})
PAID_GIFT_CHECK = Button(area={'cn': (158, 93, 478, 282)}, color={'cn': (130, 112, 89)}, button={'cn': (158, 93, 478, 282)}, file={'cn': './assets/cn/handler/PAID_GIFT_CHECK.png'})
POPUP_CHECK = Button(area={'cn': (251, 660, 460, 678)}, color={'cn': (160, 160, 160)}, button={'cn': (251, 660, 460, 678)}, file={'cn': './assets/cn/handler/POPUP_CHECK.png'})
REWARD = Button(area={'cn': (306, 408, 416, 449)}, color={'cn': (153, 154, 153)}, button={'cn': (306, 408, 416, 449)}, file={'cn': './assets/cn/handler/REWARD.png'})
SERVER_CHECK = Button(area={'cn': (297, 298, 422, 321)}, color={'cn': (164, 203, 247)}, button={'cn': (297, 298, 422, 321)}, file={'cn': './assets/cn/handler/SERVER_CHECK.png'})
SYSTEM_ERROR_CHECK = Button(area={'cn': (311, 567, 389, 585)}, color={'cn': (151, 151, 151)}, button={'cn': (311, 567, 389, 585)}, file={'cn': './assets/cn/handler/SYSTEM_ERROR_CHECK.png'})
SYSTEM_MAINTENANCE_CHECK = Button(area={'cn': (241, 589, 458, 604)}, color={'cn': (194, 193, 194)}, button={'cn': (241, 589, 458, 604)}, file={'cn': './assets/cn/handler/SYSTEM_MAINTENANCE_CHECK.png'})
