from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BATTLE_QUICKLY = Button(area={'cn': (496, 1093, 591, 1125)}, color={'cn': (254, 147, 104)}, button={'cn': (496, 1093, 591, 1125)}, file={'cn': './assets/cn/event_daemon/BATTLE_QUICKLY.png'})
FIGHT_2 = Button(area={'cn': (508, 972, 607, 1000)}, color={'cn': (91, 201, 249)}, button={'cn': (508, 972, 607, 1000)}, file={'cn': './assets/cn/event_daemon/FIGHT_2.png'})
SKIP = Button(area={'cn': (616, 22, 671, 41)}, color={'cn': (133, 134, 133)}, button={'cn': (616, 22, 671, 41)}, file={'cn': './assets/cn/event_daemon/SKIP.png'})
