from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ABNORMAL_INTERCEPTION_CHECK = Button(area={'cn': (95, 854, 256, 880)}, color={'cn': (91, 92, 92)}, button={'cn': (95, 854, 256, 880)}, file={'cn': './assets/cn/interception/ABNORMAL_INTERCEPTION_CHECK.png'})
BATTLE = Button(area={'cn': (466, 1150, 601, 1189)}, color={'cn': (244, 106, 86)}, button={'cn': (466, 1150, 601, 1189)}, file={'cn': './assets/cn/interception/BATTLE.png'})
BATTLE_QUICKLY = Button(area={'cn': (505, 1077, 603, 1106)}, color={'cn': (254, 154, 113)}, button={'cn': (505, 1077, 603, 1106)}, file={'cn': './assets/cn/interception/BATTLE_QUICKLY.png'})
KRAKEN = Button(area={'cn': (314, 299, 696, 1252)}, color={'cn': (5, 3, 3)}, button={'cn': (314, 299, 696, 1252)}, file={'cn': './assets/cn/interception/KRAKEN.png'})
KRAKEN_CHECK = Button(area={'cn': (291, 939, 428, 986)}, color={'cn': (136, 135, 133)}, button={'cn': (291, 939, 428, 986)}, file={'cn': './assets/cn/interception/KRAKEN_CHECK.png'})
TRAIN = Button(area={'cn': (226, 666, 339, 698)}, color={'cn': (162, 162, 161)}, button={'cn': (226, 666, 339, 698)}, file={'cn': './assets/cn/interception/TRAIN.png'})
