from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BATTLE = Button(area={'cn': (458, 1164, 598, 1209)}, color={'cn': (244, 93, 72)}, button={'cn': (458, 1164, 598, 1209)}, file={'cn': './assets/cn/interception/BATTLE.png'})
BATTLE_QUICKLY = Button(area={'cn': (496, 1093, 591, 1125)}, color={'cn': (254, 147, 104)}, button={'cn': (496, 1093, 591, 1125)}, file={'cn': './assets/cn/interception/BATTLE_QUICKLY.png'})
TRAIN = Button(area={'cn': (226, 666, 339, 698)}, color={'cn': (162, 162, 161)}, button={'cn': (226, 666, 339, 698)}, file={'cn': './assets/cn/interception/TRAIN.png'})
