from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BATTLE = Button(
    area={"cn": (465, 1141, 608, 1191)},
    color={"cn": (240, 92, 72)},
    button={"cn": (465, 1141, 608, 1191)},
    file={"cn": "./assets/cn/interception/BATTLE.png"},
)
BATTLE_QUICKLY = Button(
    area={"cn": (504, 1074, 602, 1106)},
    color={"cn": (254, 147, 104)},
    button={"cn": (504, 1074, 602, 1106)},
    file={"cn": "./assets/cn/interception/BATTLE_QUICKLY.png"},
)
