from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BUY = Button(area={'cn': (470, 1073, 505, 1095)}, color={'cn': (129, 199, 232)}, button={'cn': (470, 1073, 505, 1095)}, file={'cn': './assets/cn/shop/BUY.png'})
CANCEL = Button(area={'cn': (208, 789, 255, 813)}, color={'cn': (158, 157, 158)}, button={'cn': (208, 789, 255, 813)}, file={'cn': './assets/cn/shop/CANCEL.png'})
CORE_DUST_CASE = Button(area={'cn': (573, 647, 636, 669)}, color={'cn': (170, 170, 170)}, button={'cn': (573, 647, 636, 669)}, file={'cn': './assets/cn/shop/CORE_DUST_CASE.png'})
GENERAL_SHOP_CHECK = Button(area={'cn': (120, 469, 261, 517)}, color={'cn': (182, 183, 186)}, button={'cn': (120, 469, 261, 517)}, file={'cn': './assets/cn/shop/GENERAL_SHOP_CHECK.png'})
GOTO_GENERAL_SHOP = Button(area={'cn': (32, 482, 69, 517)}, color={'cn': (128, 126, 128)}, button={'cn': (32, 482, 69, 517)}, file={'cn': './assets/cn/shop/GOTO_GENERAL_SHOP.png'})
GRATIS = Button(area={'cn': (176, 836, 256, 848)}, color={'cn': (253, 194, 126)}, button={'cn': (176, 836, 256, 848)}, file={'cn': './assets/cn/shop/GRATIS.png'})
GRATIS_REFRESH = Button(area={'cn': (379, 671, 427, 697)}, color={'cn': (69, 108, 139)}, button={'cn': (379, 671, 427, 697)}, file={'cn': './assets/cn/shop/GRATIS_REFRESH.png'})
REFRESH = Button(area={'cn': (197, 576, 251, 589)}, color={'cn': (148, 147, 149)}, button={'cn': (197, 576, 251, 589)}, file={'cn': './assets/cn/shop/REFRESH.png'})
