from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ARENA_SHOP_CHECK = Button(
    area={"cn": (127, 476, 223, 504)},
    color={"cn": (137, 138, 139)},
    button={"cn": (127, 476, 223, 504)},
    file={"cn": "./assets/cn/shop/ARENA_SHOP_CHECK.png"},
)
BUY = Button(
    area={"cn": (470, 1073, 505, 1095)},
    color={"cn": (129, 199, 232)},
    button={"cn": (470, 1073, 505, 1095)},
    file={"cn": "./assets/cn/shop/BUY.png"},
)
CANCEL = Button(
    area={"cn": (208, 789, 255, 813)},
    color={"cn": (158, 157, 158)},
    button={"cn": (208, 789, 255, 813)},
    file={"cn": "./assets/cn/shop/CANCEL.png"},
)
CORE_DUST_CASE = Button(
    area={"cn": (573, 647, 636, 669)},
    color={"cn": (170, 170, 170)},
    button={"cn": (573, 647, 636, 669)},
    file={"cn": "./assets/cn/shop/CORE_DUST_CASE.png"},
)
CREDIT = Button(
    area={"cn": (561, 867, 596, 897)},
    color={"cn": (78, 77, 71)},
    button={"cn": (561, 867, 596, 897)},
    file={"cn": "./assets/cn/shop/CREDIT.png"},
)
ELECTRIC_CODE = Button(
    area={"cn": (201, 706, 239, 765)},
    color={"cn": (168, 78, 96)},
    button={"cn": (201, 706, 239, 765)},
    file={"cn": "./assets/cn/shop/ELECTRIC_CODE.png"},
)
FIRE_CODE = Button(
    area={"cn": (202, 707, 240, 768)},
    color={"cn": (161, 78, 53)},
    button={"cn": (202, 707, 240, 768)},
    file={"cn": "./assets/cn/shop/FIRE_CODE.png"},
)
GENERAL_SHOP_CHECK = Button(
    area={"cn": (126, 474, 190, 506)},
    color={"cn": (140, 140, 142)},
    button={"cn": (126, 474, 190, 506)},
    file={"cn": "./assets/cn/shop/GENERAL_SHOP_CHECK.png"},
)
GOTO_ARENA_SHOP = Button(
    area={"cn": (31, 791, 64, 817)},
    color={"cn": (124, 124, 124)},
    button={"cn": (31, 791, 64, 817)},
    file={"cn": "./assets/cn/shop/GOTO_ARENA_SHOP.png"},
)
GOTO_GENERAL_SHOP = Button(
    area={"cn": (32, 482, 69, 517)},
    color={"cn": (128, 126, 128)},
    button={"cn": (32, 482, 69, 517)},
    file={"cn": "./assets/cn/shop/GOTO_GENERAL_SHOP.png"},
)
GRATIS = Button(
    area={"cn": (176, 836, 256, 848)},
    color={"cn": (253, 194, 126)},
    button={"cn": (176, 836, 256, 848)},
    file={"cn": "./assets/cn/shop/GRATIS.png"},
)
GRATIS_B = Button(
    area={"cn": (194, 860, 247, 903)},
    color={"cn": (76, 88, 97)},
    button={"cn": (194, 860, 247, 903)},
    file={"cn": "./assets/cn/shop/GRATIS_B.png"},
)
GRATIS_REFRESH = Button(
    area={"cn": (379, 671, 427, 697)},
    color={"cn": (69, 108, 139)},
    button={"cn": (379, 671, 427, 697)},
    file={"cn": "./assets/cn/shop/GRATIS_REFRESH.png"},
)
IRON_CODE = Button(
    area={"cn": (589, 707, 621, 767)},
    color={"cn": (167, 123, 40)},
    button={"cn": (589, 707, 621, 767)},
    file={"cn": "./assets/cn/shop/IRON_CODE.png"},
)
MANUAL_SELECTION_BOX = Button(
    area={"cn": (186, 951, 243, 1001)},
    color={"cn": (188, 175, 163)},
    button={"cn": (186, 951, 243, 1001)},
    file={"cn": "./assets/cn/shop/MANUAL_SELECTION_BOX.png"},
)
MAX = Button(
    area={"cn": (576, 782, 632, 800)},
    color={"cn": (112, 112, 112)},
    button={"cn": (576, 782, 632, 800)},
    file={"cn": "./assets/cn/shop/MAX.png"},
)
NO_MONEY = Button(
    area={"cn": (450, 877, 460, 911)},
    color={"cn": (177, 45, 41)},
    button={"cn": (450, 877, 460, 911)},
    file={"cn": "./assets/cn/shop/NO_MONEY.png"},
)
PURCHASE_CHECK = Button(
    area={"cn": (308, 211, 412, 242)},
    color={"cn": (115, 167, 227)},
    button={"cn": (308, 211, 412, 242)},
    file={"cn": "./assets/cn/shop/PURCHASE_CHECK.png"},
)
REFRESH = Button(
    area={"cn": (402, 571, 425, 593)},
    color={"cn": (109, 111, 113)},
    button={"cn": (402, 571, 425, 593)},
    file={"cn": "./assets/cn/shop/REFRESH.png"},
)
WATER_CODE = Button(
    area={"cn": (394, 706, 430, 768)},
    color={"cn": (94, 116, 133)},
    button={"cn": (394, 706, 430, 768)},
    file={"cn": "./assets/cn/shop/WATER_CODE.png"},
)
WIND_CODE = Button(
    area={"cn": (395, 708, 431, 766)},
    color={"cn": (94, 147, 44)},
    button={"cn": (395, 708, 431, 766)},
    file={"cn": "./assets/cn/shop/WIND_CODE.png"},
)
