from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ARENA_SHOP_CHECK = Button(area={'cn': (127, 476, 284, 504)}, color={'cn': (135, 136, 138)}, button={'cn': (127, 476, 284, 504)}, file={'cn': './assets/cn/shop/ARENA_SHOP_CHECK.png'})
BUY = Button(area={'cn': (470, 1073, 505, 1095)}, color={'cn': (129, 199, 232)}, button={'cn': (470, 1073, 505, 1095)}, file={'cn': './assets/cn/shop/BUY.png'})
CANCEL = Button(area={'cn': (208, 789, 255, 813)}, color={'cn': (158, 157, 158)}, button={'cn': (208, 789, 255, 813)}, file={'cn': './assets/cn/shop/CANCEL.png'})
CORE_DUST_CASE = Button(area={'cn': (573, 647, 636, 669)}, color={'cn': (170, 170, 170)}, button={'cn': (573, 647, 636, 669)}, file={'cn': './assets/cn/shop/CORE_DUST_CASE.png'})
ELECTRIC_CODE = Button(area={'cn': (531, 648, 672, 675)}, color={'cn': (213, 214, 215)}, button={'cn': (531, 648, 672, 675)}, file={'cn': './assets/cn/shop/ELECTRIC_CODE.png'})
FIRE_CODE = Button(area={'cn': (138, 649, 293, 666)}, color={'cn': (174, 175, 176)}, button={'cn': (138, 649, 293, 666)}, file={'cn': './assets/cn/shop/FIRE_CODE.png'})
GENERAL_SHOP_CHECK = Button(area={'cn': (120, 469, 261, 517)}, color={'cn': (182, 183, 186)}, button={'cn': (120, 469, 261, 517)}, file={'cn': './assets/cn/shop/GENERAL_SHOP_CHECK.png'})
GOTO_ARENA_SHOP = Button(area={'cn': (31, 791, 64, 817)}, color={'cn': (124, 124, 124)}, button={'cn': (31, 791, 64, 817)}, file={'cn': './assets/cn/shop/GOTO_ARENA_SHOP.png'})
GOTO_GENERAL_SHOP = Button(area={'cn': (32, 482, 69, 517)}, color={'cn': (128, 126, 128)}, button={'cn': (32, 482, 69, 517)}, file={'cn': './assets/cn/shop/GOTO_GENERAL_SHOP.png'})
GRATIS = Button(area={'cn': (176, 836, 256, 848)}, color={'cn': (253, 194, 126)}, button={'cn': (176, 836, 256, 848)}, file={'cn': './assets/cn/shop/GRATIS.png'})
GRATIS_REFRESH = Button(area={'cn': (379, 671, 427, 697)}, color={'cn': (69, 108, 139)}, button={'cn': (379, 671, 427, 697)}, file={'cn': './assets/cn/shop/GRATIS_REFRESH.png'})
IRON_CODE = Button(area={'cn': (525, 648, 684, 668)}, color={'cn': (183, 184, 184)}, button={'cn': (525, 648, 684, 668)}, file={'cn': './assets/cn/shop/IRON_CODE.png'})
MANUAL_SELECTION_BOX = Button(area={'cn': (151, 955, 285, 979)}, color={'cn': (191, 192, 193)}, button={'cn': (151, 955, 285, 979)}, file={'cn': './assets/cn/shop/MANUAL_SELECTION_BOX.png'})
MAX = Button(area={'cn': (576, 782, 632, 800)}, color={'cn': (112, 112, 112)}, button={'cn': (576, 782, 632, 800)}, file={'cn': './assets/cn/shop/MAX.png'})
NO_MONEY = Button(area={'cn': (450, 877, 460, 911)}, color={'cn': (177, 45, 41)}, button={'cn': (450, 877, 460, 911)}, file={'cn': './assets/cn/shop/NO_MONEY.png'})
REFRESH = Button(area={'cn': (197, 576, 251, 589)}, color={'cn': (148, 147, 149)}, button={'cn': (197, 576, 251, 589)}, file={'cn': './assets/cn/shop/REFRESH.png'})
WATER_CODE = Button(area={'cn': (336, 646, 480, 676)}, color={'cn': (214, 215, 216)}, button={'cn': (336, 646, 480, 676)}, file={'cn': './assets/cn/shop/WATER_CODE.png'})
WIND_CODE = Button(area={'cn': (148, 647, 286, 674)}, color={'cn': (211, 212, 213)}, button={'cn': (148, 647, 286, 674)}, file={'cn': './assets/cn/shop/WIND_CODE.png'})
