from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

GOTO_RUBBISH_SHOP = Button(area={'cn': (31, 990, 71, 1025)}, color={'cn': (141, 141, 143)}, button={'cn': (31, 990, 71, 1025)}, file={'cn': './assets/cn/rubbish_shop/GOTO_RUBBISH_SHOP.png'})
NO_MONEY = Button(area={'cn': (450, 877, 460, 911)}, color={'cn': (177, 45, 41)}, button={'cn': (450, 877, 460, 911)}, file={'cn': './assets/cn/rubbish_shop/NO_MONEY.png'})
RUBBISH_SHOP_CHECK = Button(area={'cn': (121, 471, 254, 511)}, color={'cn': (165, 166, 168)}, button={'cn': (121, 471, 254, 511)}, file={'cn': './assets/cn/rubbish_shop/RUBBISH_SHOP_CHECK.png'})
