from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ABNORMAL_TICKET = Button(
    area={"cn": (168, 867, 265, 898)},
    color={"cn": (198, 199, 200)},
    button={"cn": (168, 867, 265, 898)},
    file={"cn": "./assets/cn/rubbish_shop/ABNORMAL_TICKET.png"},
)
BATTLE_DATA_SET_CASE = Button(
    area={"cn": (541, 816, 605, 837)},
    color={"cn": (165, 165, 166)},
    button={"cn": (541, 816, 605, 837)},
    file={"cn": "./assets/cn/rubbish_shop/BATTLE_DATA_SET_CASE.png"},
)
BUY = Button(
    area={"cn": (469, 1044, 516, 1059)},
    color={"cn": (133, 202, 235)},
    button={"cn": (469, 1044, 516, 1059)},
    file={"cn": "./assets/cn/rubbish_shop/BUY.png"},
)
CANCEL = Button(
    area={"cn": (246, 1044, 290, 1067)},
    color={"cn": (156, 156, 158)},
    button={"cn": (246, 1044, 290, 1067)},
    file={"cn": "./assets/cn/rubbish_shop/CANCEL.png"},
)
CORE_DUST_CASE = Button(
    area={"cn": (183, 886, 225, 907)},
    color={"cn": (173, 173, 175)},
    button={"cn": (183, 886, 225, 907)},
    file={"cn": "./assets/cn/rubbish_shop/CORE_DUST_CASE.png"},
)
CREDIT_CASE = Button(
    area={"cn": (377, 885, 443, 908)},
    color={"cn": (171, 171, 172)},
    button={"cn": (377, 885, 443, 908)},
    file={"cn": "./assets/cn/rubbish_shop/CREDIT_CASE.png"},
)
ELYSION_TICKET = Button(
    area={"cn": (524, 643, 686, 671)},
    color={"cn": (194, 195, 196)},
    button={"cn": (524, 643, 686, 671)},
    file={"cn": "./assets/cn/rubbish_shop/ELYSION_TICKET.png"},
)
GEM = Button(
    area={"cn": (192, 646, 239, 671)},
    color={"cn": (179, 180, 181)},
    button={"cn": (192, 646, 239, 671)},
    file={"cn": "./assets/cn/rubbish_shop/GEM.png"},
)
GENERAL_TICKET = Button(
    area={"cn": (347, 645, 474, 668)},
    color={"cn": (159, 160, 161)},
    button={"cn": (347, 645, 474, 668)},
    file={"cn": "./assets/cn/rubbish_shop/GENERAL_TICKET.png"},
)
GOTO_RUBBISH_SHOP = Button(
    area={"cn": (31, 990, 71, 1025)},
    color={"cn": (141, 141, 143)},
    button={"cn": (31, 990, 71, 1025)},
    file={"cn": "./assets/cn/rubbish_shop/GOTO_RUBBISH_SHOP.png"},
)
MISSILIS_TICKET = Button(
    area={"cn": (146, 953, 289, 976)},
    color={"cn": (175, 176, 178)},
    button={"cn": (146, 953, 289, 976)},
    file={"cn": "./assets/cn/rubbish_shop/MISSILIS_TICKET.png"},
)
PILGRIM_TICKET = Button(
    area={"cn": (525, 953, 687, 970)},
    color={"cn": (161, 161, 161)},
    button={"cn": (525, 953, 687, 970)},
    file={"cn": "./assets/cn/rubbish_shop/PILGRIM_TICKET.png"},
)
RUBBISH_SHOP_CHECK = Button(
    area={"cn": (127, 474, 190, 506)},
    color={"cn": (137, 137, 139)},
    button={"cn": (127, 474, 190, 506)},
    file={"cn": "./assets/cn/rubbish_shop/RUBBISH_SHOP_CHECK.png"},
)
TETRA_TICKET = Button(
    area={"cn": (332, 951, 492, 978)},
    color={"cn": (186, 187, 188)},
    button={"cn": (332, 951, 492, 978)},
    file={"cn": "./assets/cn/rubbish_shop/TETRA_TICKET.png"},
)
