from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ADMI = Button(area={'cn': (0, 0, 54, 20)}, color={'cn': (158, 116, 33)}, button={'cn': (0, 0, 54, 20)}, file={'cn': './assets/cn/nikke_switch/ADMI.png'})
ATTACKER = Button(area={'cn': (0, 0, 107, 48)}, color={'cn': (23, 182, 255)}, button={'cn': (0, 0, 107, 48)}, file={'cn': './assets/cn/nikke_switch/ATTACKER.png'})
SR = Button(area={'cn': (0, 0, 65, 34)}, color={'cn': (24, 182, 255)}, button={'cn': (0, 0, 65, 34)}, file={'cn': './assets/cn/nikke_switch/SR.png'})
Tetra = Button(area={'cn': (0, 0, 109, 48)}, color={'cn': (29, 183, 255)}, button={'cn': (0, 0, 109, 48)}, file={'cn': './assets/cn/nikke_switch/Tetra.png'})
