# ==================== Reward ====================

Reward:
  Scheduler:
    Enable: true

Destroy:
  Scheduler:
    Enable: false

Commission:
  Scheduler:
    Enable: false

RookieArena:
  Scheduler:
    Enable: false

Conversation:
  Scheduler:
    Enable: false

SimulationRoom:
  Scheduler:
    Enable: false

TribeTower:
  Scheduler:
    Enable: false

RedeemCodes:
  Scheduler:
    Enable: true

Daily:
  Scheduler:
    Enable: false

RubbishShop:
  Scheduler:
    Enable: false

MissionPass:
  Scheduler:
    Enable: false

Liberation:
  Scheduler:
    Enable: false

DailyGift:
  Scheduler:
    Enable: false

WeeklyGift:
  Scheduler:
    Enable: false

MonthlyGift:
  Scheduler:
    Enable: false