from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ANSWER_CHECK = Button(area={'cn': (70, 818, 88, 894)}, color={'cn': (7, 24, 35)}, button={'cn': (70, 818, 88, 894)}, file={'cn': './assets/cn/conversation/ANSWER_CHECK.png'})
CASE_CLOSED = Button(area={'cn': (583, 637, 686, 647)}, color={'cn': (103, 205, 250)}, button={'cn': (583, 637, 686, 647)}, file={'cn': './assets/cn/conversation/CASE_CLOSED.png'})
COMMUNICATE = Button(area={'cn': (460, 1017, 559, 1064)}, color={'cn': (87, 149, 207)}, button={'cn': (460, 1017, 559, 1064)}, file={'cn': './assets/cn/conversation/COMMUNICATE.png'})
DETAIL_CHECK = Button(area={'cn': (514, 1173, 621, 1197)}, color={'cn': (254, 141, 129)}, button={'cn': (514, 1173, 621, 1197)}, file={'cn': './assets/cn/conversation/DETAIL_CHECK.png'})
FAVOURITE_CHECK = Button(area={'cn': (27, 394, 45, 499)}, color={'cn': (254, 98, 83)}, button={'cn': (27, 394, 45, 499)}, file={'cn': './assets/cn/conversation/FAVOURITE_CHECK.png'})
GIFT = Button(area={'cn': (160, 1018, 225, 1059)}, color={'cn': (254, 177, 79)}, button={'cn': (160, 1018, 225, 1059)}, file={'cn': './assets/cn/conversation/GIFT.png'})
OPPORTUNITY = Button(area={'cn': (83, 295, 183, 325)}, color={'cn': (70, 192, 249)}, button={'cn': (83, 295, 183, 325)}, file={'cn': './assets/cn/conversation/OPPORTUNITY.png'})
OPPORTUNITY_B = Button(area={'cn': (506, 1068, 541, 1087)}, color={'cn': (192, 191, 194)}, button={'cn': (506, 1068, 541, 1087)}, file={'cn': './assets/cn/conversation/OPPORTUNITY_B.png'})
RANK_INCREASE_CHECK = Button(area={'cn': (252, 559, 416, 618)}, color={'cn': (67, 39, 57)}, button={'cn': (252, 559, 416, 618)}, file={'cn': './assets/cn/conversation/RANK_INCREASE_CHECK.png'})
RANK_INCREASE_COMFIRM = Button(area={'cn': (272, 1109, 448, 1148)}, color={'cn': (209, 206, 209)}, button={'cn': (272, 1109, 448, 1148)}, file={'cn': './assets/cn/conversation/RANK_INCREASE_COMFIRM.png'})
RANK_MAX_CHECK = Button(area={'cn': (603, 866, 636, 889)}, color={'cn': (252, 200, 196)}, button={'cn': (603, 866, 636, 889)}, file={'cn': './assets/cn/conversation/RANK_MAX_CHECK.png'})
