from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ANIS_SPARKLING_SUMMER = Button(area={'cn': (0, 0, 206, 27)}, color={'cn': (150, 0, 0)}, button={'cn': (0, 0, 206, 27)}, file={'cn': './assets/cn/conversation/ANIS_SPARKLING_SUMMER.png'})
ANSWER_CHECK = Button(area={'cn': (70, 818, 88, 894)}, color={'cn': (7, 24, 35)}, button={'cn': (70, 818, 88, 894)}, file={'cn': './assets/cn/conversation/ANSWER_CHECK.png'})
CASE_CLOSED = Button(area={'cn': (583, 637, 686, 647)}, color={'cn': (103, 205, 250)}, button={'cn': (583, 637, 686, 647)}, file={'cn': './assets/cn/conversation/CASE_CLOSED.png'})
COMMUNICATE = Button(area={'cn': (512, 1046, 574, 1086)}, color={'cn': (73, 189, 236)}, button={'cn': (512, 1046, 574, 1086)}, file={'cn': './assets/cn/conversation/COMMUNICATE.png'})
D = Button(area={'cn': (0, 0, 19, 22)}, color={'cn': (147, 0, 0)}, button={'cn': (0, 0, 19, 22)}, file={'cn': './assets/cn/conversation/D.png'})
DETAIL_CHECK = Button(area={'cn': (508, 962, 597, 980)}, color={'cn': (127, 142, 161)}, button={'cn': (508, 962, 597, 980)}, file={'cn': './assets/cn/conversation/DETAIL_CHECK.png'})
FAVOURITE_CHECK = Button(area={'cn': (27, 394, 45, 499)}, color={'cn': (254, 98, 83)}, button={'cn': (27, 394, 45, 499)}, file={'cn': './assets/cn/conversation/FAVOURITE_CHECK.png'})
NERO = Button(area={'cn': (0, 0, 52, 26)}, color={'cn': (149, 0, 0)}, button={'cn': (0, 0, 52, 26)}, file={'cn': './assets/cn/conversation/NERO.png'})
OPPORTUNITY = Button(area={'cn': (83, 295, 183, 325)}, color={'cn': (70, 192, 249)}, button={'cn': (83, 295, 183, 325)}, file={'cn': './assets/cn/conversation/OPPORTUNITY.png'})
RANK_INCREASE_CHECK = Button(area={'cn': (252, 559, 416, 618)}, color={'cn': (67, 39, 57)}, button={'cn': (252, 559, 416, 618)}, file={'cn': './assets/cn/conversation/RANK_INCREASE_CHECK.png'})
RANK_INCREASE_COMFIRM = Button(area={'cn': (272, 1109, 448, 1148)}, color={'cn': (209, 206, 209)}, button={'cn': (272, 1109, 448, 1148)}, file={'cn': './assets/cn/conversation/RANK_INCREASE_COMFIRM.png'})
RANK_MAX_CHECK = Button(area={'cn': (603, 866, 636, 889)}, color={'cn': (252, 200, 196)}, button={'cn': (603, 866, 636, 889)}, file={'cn': './assets/cn/conversation/RANK_MAX_CHECK.png'})
RUPEE = Button(area={'cn': (0, 0, 53, 27)}, color={'cn': (134, 0, 0)}, button={'cn': (0, 0, 53, 27)}, file={'cn': './assets/cn/conversation/RUPEE.png'})
RUPEE_WINTER_SHOPPER = Button(area={'cn': (0, 0, 209, 27)}, color={'cn': (156, 0, 0)}, button={'cn': (0, 0, 209, 27)}, file={'cn': './assets/cn/conversation/RUPEE_WINTER_SHOPPER.png'})
