from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

END_COMPETITION = Button(area={'cn': (45, 1194, 86, 1236)}, color={'cn': (117, 116, 117)}, button={'cn': (45, 1194, 86, 1236)}, file={'cn': './assets/cn/rookie_arena/END_COMPETITION.png'})
FREE_OPPORTUNITY_CHECK = Button(area={'cn': (580, 677, 619, 698)}, color={'cn': (120, 195, 237)}, button={'cn': (580, 677, 619, 698)}, file={'cn': './assets/cn/rookie_arena/FREE_OPPORTUNITY_CHECK.png'})
INTO_COMPETITION = Button(area={'cn': (294, 1035, 421, 1064)}, color={'cn': (130, 178, 219)}, button={'cn': (294, 1035, 421, 1064)}, file={'cn': './assets/cn/rookie_arena/INTO_COMPETITION.png'})
NEXT_SEASON = Button(area={'cn': (146, 588, 212, 603)}, color={'cn': (48, 55, 58)}, button={'cn': (146, 588, 212, 603)}, file={'cn': './assets/cn/rookie_arena/NEXT_SEASON.png'})
OWN_POWER_CHECK = Button(area={'cn': (530, 369, 550, 388)}, color={'cn': (117, 120, 122)}, button={'cn': (530, 369, 550, 388)}, file={'cn': './assets/cn/rookie_arena/OWN_POWER_CHECK.png'})
POWER_CHECK = Button(area={'cn': (428, 668, 446, 686)}, color={'cn': (195, 196, 197)}, button={'cn': (428, 668, 446, 686)}, file={'cn': './assets/cn/rookie_arena/POWER_CHECK.png'})
SKIP = Button(area={'cn': (226, 1060, 276, 1077)}, color={'cn': (148, 148, 148)}, button={'cn': (226, 1060, 276, 1077)}, file={'cn': './assets/cn/rookie_arena/SKIP.png'})
