from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

CLICK_REDEEM = Button(area={'cn': (305, 847, 326, 879)}, color={'cn': (95, 165, 214)}, button={'cn': (305, 847, 326, 879)}, file={'cn': './assets/cn/redeem_codes/CLICK_REDEEM.png'})
CODE_REDEEMED = Button(area={'cn': (328, 736, 362, 773)}, color={'cn': (137, 206, 255)}, button={'cn': (328, 736, 362, 773)}, file={'cn': './assets/cn/redeem_codes/CODE_REDEEMED.png'})
FIND_CDKEY = Button(area={'cn': (160, 769, 187, 788)}, color={'cn': (130, 78, 75)}, button={'cn': (160, 769, 187, 788)}, file={'cn': './assets/cn/redeem_codes/FIND_CDKEY.png'})
GO_TO_REDEEM = Button(area={'cn': (407, 474, 436, 502)}, color={'cn': (130, 130, 130)}, button={'cn': (407, 474, 436, 502)}, file={'cn': './assets/cn/redeem_codes/GO_TO_REDEEM.png'})
NOTICE_BUTTON = Button(area={'cn': (547, 44, 585, 62)}, color={'cn': (54, 53, 50)}, button={'cn': (547, 44, 585, 62)}, file={'cn': './assets/cn/redeem_codes/NOTICE_BUTTON.png'})
NOTICE_OPEN = Button(area={'cn': (314, 131, 349, 153)}, color={'cn': (21, 82, 150)}, button={'cn': (314, 131, 349, 153)}, file={'cn': './assets/cn/redeem_codes/NOTICE_OPEN.png'})
WRITE_CD_KEY = Button(area={'cn': (425, 538, 466, 563)}, color={'cn': (226, 226, 226)}, button={'cn': (425, 538, 466, 563)}, file={'cn': './assets/cn/redeem_codes/WRITE_CD_KEY.png'})
