from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

CONFRIM_A = Button(area={'cn': (354, 819, 405, 844)}, color={'cn': (126, 214, 255)},
                   button={'cn': (354, 819, 405, 844)}, file={'cn': './assets/cn/ui/CONFRIM_A.png'})
MAIN_CHECK = Button(area={'cn': (38, 359, 87, 394)}, color={'cn': (34, 83, 113)}, button={'cn': (38, 359, 87, 394)},
                    file={'cn': './assets/cn/ui/MAIN_CHECK.png'})
REWARD = Button(area={'cn': (306, 408, 416, 449)}, color={'cn': (153, 154, 153)}, button={'cn': (306, 408, 416, 449)},
                file={'cn': './assets/cn/ui/REWARD.png'})
