from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

CONFRIM_A = Button(area={'cn': (354, 819, 405, 844)}, color={'cn': (126, 214, 255)}, button={'cn': (354, 819, 405, 844)}, file={'cn': './assets/cn/ui/CONFRIM_A.png'})
GOTO_MAIN = Button(area={'cn': (181, 1194, 212, 1223)}, color={'cn': (117, 199, 239)}, button={'cn': (181, 1194, 212, 1223)}, file={'cn': './assets/cn/ui/GOTO_MAIN.png'})
MAIN_CHECK = Button(area={'cn': (38, 359, 87, 394)}, color={'cn': (34, 83, 113)}, button={'cn': (38, 359, 87, 394)}, file={'cn': './assets/cn/ui/MAIN_CHECK.png'})
MAIN_GOTO_REWARD = Button(area={'cn': (127, 1040, 146, 1078)}, color={'cn': (100, 100, 99)}, button={'cn': (127, 1040, 146, 1078)}, file={'cn': './assets/cn/ui/MAIN_GOTO_REWARD.png'})
REWARD = Button(area={'cn': (306, 408, 416, 449)}, color={'cn': (153, 154, 153)}, button={'cn': (306, 408, 416, 449)}, file={'cn': './assets/cn/ui/REWARD.png'})
REWARD_CHECK = Button(area={'cn': (96, 307, 333, 342)}, color={'cn': (163, 165, 167)}, button={'cn': (96, 307, 333, 342)}, file={'cn': './assets/cn/ui/REWARD_CHECK.png'})
REWARD_GOTO_MAIN = Button(area={'cn': (627, 166, 665, 203)}, color={'cn': (59, 148, 224)}, button={'cn': (627, 166, 665, 203)}, file={'cn': './assets/cn/ui/REWARD_GOTO_MAIN.png'})
