from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ARENA_CHECK = Button(area={'cn': (69, 656, 160, 696)}, color={'cn': (104, 109, 124)}, button={'cn': (69, 656, 160, 696)}, file={'cn': './assets/cn/ui/ARENA_CHECK.png'})
ARENA_GOTO_SPECIAL_ARENA = Button(area={'cn': (399, 659, 500, 689)}, color={'cn': (112, 117, 130)}, button={'cn': (399, 659, 500, 689)}, file={'cn': './assets/cn/ui/ARENA_GOTO_SPECIAL_ARENA.png'})
ARK_CHECK = Button(area={'cn': (59, 588, 71, 646)}, color={'cn': (106, 106, 105)}, button={'cn': (59, 588, 71, 646)}, file={'cn': './assets/cn/ui/ARK_CHECK.png'})
ARK_GOTO_ARENA = Button(area={'cn': (445, 710, 457, 787)}, color={'cn': (107, 107, 106)}, button={'cn': (445, 710, 457, 787)}, file={'cn': './assets/cn/ui/ARK_GOTO_ARENA.png'})
FRIEND_CHECK = Button(area={'cn': (311, 147, 414, 175)}, color={'cn': (125, 174, 231)}, button={'cn': (311, 147, 414, 175)}, file={'cn': './assets/cn/ui/FRIEND_CHECK.png'})
FRIEND_GOTO_MAIN = Button(area={'cn': (621, 139, 661, 178)}, color={'cn': (56, 145, 223)}, button={'cn': (621, 139, 661, 178)}, file={'cn': './assets/cn/ui/FRIEND_GOTO_MAIN.png'})
GOTO_BACK = Button(area={'cn': (29, 1193, 53, 1222)}, color={'cn': (120, 197, 235)}, button={'cn': (29, 1193, 53, 1222)}, file={'cn': './assets/cn/ui/GOTO_BACK.png'})
GOTO_MAIN = Button(area={'cn': (181, 1194, 212, 1223)}, color={'cn': (117, 199, 239)}, button={'cn': (181, 1194, 212, 1223)}, file={'cn': './assets/cn/ui/GOTO_MAIN.png'})
MAIN_CHECK = Button(area={'cn': (38, 359, 87, 394)}, color={'cn': (34, 83, 113)}, button={'cn': (38, 359, 87, 394)}, file={'cn': './assets/cn/ui/MAIN_CHECK.png'})
MAIN_GOTO_ARK = Button(area={'cn': (504, 847, 530, 877)}, color={'cn': (128, 131, 133)}, button={'cn': (504, 847, 530, 877)}, file={'cn': './assets/cn/ui/MAIN_GOTO_ARK.png'})
MAIN_GOTO_FRIEND = Button(area={'cn': (638, 289, 678, 328)}, color={'cn': (203, 205, 207)}, button={'cn': (638, 289, 678, 328)}, file={'cn': './assets/cn/ui/MAIN_GOTO_FRIEND.png'})
MAIN_GOTO_REWARD = Button(area={'cn': (127, 1040, 146, 1078)}, color={'cn': (100, 100, 99)}, button={'cn': (127, 1040, 146, 1078)}, file={'cn': './assets/cn/ui/MAIN_GOTO_REWARD.png'})
REWARD_CHECK = Button(area={'cn': (96, 307, 333, 342)}, color={'cn': (163, 165, 167)}, button={'cn': (96, 307, 333, 342)}, file={'cn': './assets/cn/ui/REWARD_CHECK.png'})
REWARD_GOTO_MAIN = Button(area={'cn': (627, 166, 665, 203)}, color={'cn': (59, 148, 224)}, button={'cn': (627, 166, 665, 203)}, file={'cn': './assets/cn/ui/REWARD_GOTO_MAIN.png'})
SPECIAL_ARENA_CHECK = Button(area={'cn': (204, 138, 524, 229)}, color={'cn': (87, 90, 97)}, button={'cn': (204, 138, 524, 229)}, file={'cn': './assets/cn/ui/SPECIAL_ARENA_CHECK.png'})
