from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

DESTROY = Button(area={'cn': (305, 931, 629, 996)}, color={'cn': (28, 179, 247)}, button={'cn': (305, 931, 629, 996)}, file={'cn': './assets/cn/destroy/DESTROY.png'})
DESTROY_CHECK = Button(area={'cn': (310, 1015, 368, 1071)}, color={'cn': (240, 237, 239)}, button={'cn': (310, 1015, 368, 1071)}, file={'cn': './assets/cn/destroy/DESTROY_CHECK.png'})
