from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

RECEIVE = Button(area={'cn': (426, 1047, 471, 1090)}, color={'cn': (67, 191, 249)}, button={'cn': (426, 1047, 471, 1090)}, file={'cn': './assets/cn/reward/RECEIVE.png'})
