from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

NO_REWARDS = Button(area={'cn': (386, 531, 632, 568)}, color={'cn': (191, 179, 178)}, button={'cn': (386, 531, 632, 568)}, file={'cn': './assets/cn/reward/NO_REWARDS.png'})
NO_REWARDS_2 = Button(area={'cn': (620, 750, 663, 786)}, color={'cn': (81, 84, 93)}, button={'cn': (620, 750, 663, 786)}, file={'cn': './assets/cn/reward/NO_REWARDS_2.png'})
RECEIVE = Button(area={'cn': (426, 1047, 471, 1090)}, color={'cn': (67, 191, 249)}, button={'cn': (426, 1047, 471, 1090)}, file={'cn': './assets/cn/reward/RECEIVE.png'})
RECEIVE_SPECIAL_ARENA_POINT = Button(area={'cn': (306, 283, 417, 292)}, color={'cn': (155, 161, 164)}, button={'cn': (306, 283, 417, 292)}, file={'cn': './assets/cn/reward/RECEIVE_SPECIAL_ARENA_POINT.png'})
REWARD = Button(area={'cn': (445, 1125, 541, 1150)}, color={'cn': (128, 198, 233)}, button={'cn': (445, 1125, 541, 1150)}, file={'cn': './assets/cn/reward/REWARD.png'})
SEND_AND_RECEIVE = Button(area={'cn': (508, 1075, 589, 1101)}, color={'cn': (129, 213, 251)}, button={'cn': (508, 1075, 589, 1101)}, file={'cn': './assets/cn/reward/SEND_AND_RECEIVE.png'})
