from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

CLAIM = Button(area={'cn': (487, 1060, 516, 1090)}, color={'cn': (73, 197, 255)}, button={'cn': (487, 1060, 516, 1090)}, file={'cn': './assets/cn/commission/CLAIM.png'})
DISPATCH = Button(area={'cn': (290, 1061, 417, 1091)}, color={'cn': (158, 224, 255)}, button={'cn': (290, 1061, 417, 1091)}, file={'cn': './assets/cn/commission/DISPATCH.png'})
DISPATCH_CONFIRM = Button(area={'cn': (383, 1058, 504, 1095)}, color={'cn': (70, 196, 255)}, button={'cn': (383, 1058, 504, 1095)}, file={'cn': './assets/cn/commission/DISPATCH_CONFIRM.png'})
enter = Button(area={'cn': (1060, 353, 1138, 373)}, color={'cn': (113, 113, 113)}, button={'cn': (1060, 353, 1138, 373)}, file={'cn': './assets/cn/commission/enter.png'})
enter_2 = Button(area={'cn': (1061, 664, 1183, 692)}, color={'cn': (156, 139, 70)}, button={'cn': (1061, 664, 1183, 692)}, file={'cn': './assets/cn/commission/enter_2.png'})
match = Button(area={'cn': (851, 616, 996, 657)}, color={'cn': (105, 102, 102)}, button={'cn': (851, 616, 996, 657)}, file={'cn': './assets/cn/commission/match.png'})
pause = Button(area={'cn': (1212, 26, 1244, 64)}, color={'cn': (175, 172, 167)}, button={'cn': (1212, 26, 1244, 64)}, file={'cn': './assets/cn/commission/pause.png'})
retreat = Button(area={'cn': (634, 619, 690, 652)}, color={'cn': (107, 98, 147)}, button={'cn': (634, 619, 690, 652)}, file={'cn': './assets/cn/commission/retreat.png'})
retreat_2 = Button(area={'cn': (795, 462, 840, 485)}, color={'cn': (143, 144, 80)}, button={'cn': (795, 462, 840, 485)}, file={'cn': './assets/cn/commission/retreat_2.png'})
vacant = Button(area={'cn': (502, 311, 739, 412)}, color={'cn': (79, 79, 79)}, button={'cn': (502, 311, 739, 412)}, file={'cn': './assets/cn/commission/vacant.png'})
