from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ABANDON = Button(area={'cn': (139, 1164, 165, 1194)}, color={'cn': (146, 145, 146)}, button={'cn': (139, 1164, 165, 1194)}, file={'cn': './assets/cn/tribe_tower/ABANDON.png'})
BACK = Button(area={'cn': (33, 1171, 70, 1206)}, color={'cn': (78, 80, 78)}, button={'cn': (33, 1171, 70, 1206)}, file={'cn': './assets/cn/tribe_tower/BACK.png'})
ELYSION_CHECK = Button(area={'cn': (59, 996, 113, 1086)}, color={'cn': (50, 74, 85)}, button={'cn': (59, 996, 113, 1086)}, file={'cn': './assets/cn/tribe_tower/ELYSION_CHECK.png'})
END_CHECK = Button(area={'cn': (261, 1118, 459, 1137)}, color={'cn': (86, 86, 86)}, button={'cn': (261, 1118, 459, 1137)}, file={'cn': './assets/cn/tribe_tower/END_CHECK.png'})
FIGHT = Button(area={'cn': (489, 1158, 611, 1187)}, color={'cn': (135, 179, 220)}, button={'cn': (489, 1158, 611, 1187)}, file={'cn': './assets/cn/tribe_tower/FIGHT.png'})
MISSILIS_CHECK = Button(area={'cn': (223, 996, 278, 1086)}, color={'cn': (50, 75, 87)}, button={'cn': (223, 996, 278, 1086)}, file={'cn': './assets/cn/tribe_tower/MISSILIS_CHECK.png'})
NEXT_STAGE = Button(area={'cn': (552, 1196, 647, 1218)}, color={'cn': (73, 190, 255)}, button={'cn': (552, 1196, 647, 1218)}, file={'cn': './assets/cn/tribe_tower/NEXT_STAGE.png'})
OPERATION_FAILED = Button(area={'cn': (102, 414, 613, 455)}, color={'cn': (75, 7, 6)}, button={'cn': (102, 414, 613, 455)}, file={'cn': './assets/cn/tribe_tower/OPERATION_FAILED.png'})
OPPORTUNITY_0 = Button(area={'cn': (0, 0, 52, 19)}, color={'cn': (38, 58, 58)}, button={'cn': (0, 0, 52, 19)}, file={'cn': './assets/cn/tribe_tower/OPPORTUNITY_0.png'})
OPPORTUNITY_1 = Button(area={'cn': (0, 0, 51, 20)}, color={'cn': (38, 54, 51)}, button={'cn': (0, 0, 51, 20)}, file={'cn': './assets/cn/tribe_tower/OPPORTUNITY_1.png'})
OPPORTUNITY_2 = Button(area={'cn': (0, 0, 52, 19)}, color={'cn': (39, 56, 55)}, button={'cn': (0, 0, 52, 19)}, file={'cn': './assets/cn/tribe_tower/OPPORTUNITY_2.png'})
OPPORTUNITY_3 = Button(area={'cn': (0, 0, 52, 19)}, color={'cn': (39, 57, 55)}, button={'cn': (0, 0, 52, 19)}, file={'cn': './assets/cn/tribe_tower/OPPORTUNITY_3.png'})
PILGRIM_CHECK = Button(area={'cn': (554, 996, 608, 1087)}, color={'cn': (50, 75, 86)}, button={'cn': (554, 996, 608, 1087)}, file={'cn': './assets/cn/tribe_tower/PILGRIM_CHECK.png'})
STAGE_INFO_CHECK = Button(area={'cn': (85, 693, 173, 737)}, color={'cn': (158, 158, 158)}, button={'cn': (85, 693, 173, 737)}, file={'cn': './assets/cn/tribe_tower/STAGE_INFO_CHECK.png'})
TETRA_CHECK = Button(area={'cn': (397, 996, 436, 1087)}, color={'cn': (51, 74, 84)}, button={'cn': (397, 996, 436, 1087)}, file={'cn': './assets/cn/tribe_tower/TETRA_CHECK.png'})
TRIBE_TOWER_DETAILED_CHECK = Button(area={'cn': (199, 526, 240, 544)}, color={'cn': (84, 85, 84)}, button={'cn': (199, 526, 240, 544)}, file={'cn': './assets/cn/tribe_tower/TRIBE_TOWER_DETAILED_CHECK.png'})
