from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

COMPLETED_1 = Button(area={'cn': (496, 834, 529, 852)}, color={'cn': (106, 89, 40)}, button={'cn': (496, 834, 529, 852)}, file={'cn': './assets/cn/liberation/COMPLETED_1.png'})
COMPLETED_2 = Button(area={'cn': (497, 914, 526, 928)}, color={'cn': (104, 46, 146)}, button={'cn': (497, 914, 526, 928)}, file={'cn': './assets/cn/liberation/COMPLETED_2.png'})
COMPLETED_3 = Button(area={'cn': (497, 991, 527, 1007)}, color={'cn': (27, 96, 129)}, button={'cn': (497, 991, 527, 1007)}, file={'cn': './assets/cn/liberation/COMPLETED_3.png'})
