from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

COMPLETED_1 = Button(area={'cn': (496, 834, 529, 852)}, color={'cn': (106, 89, 40)}, button={'cn': (496, 834, 529, 852)}, file={'cn': './assets/cn/liberation/COMPLETED_1.png'})
COMPLETED_2 = Button(area={'cn': (497, 914, 526, 928)}, color={'cn': (104, 46, 146)}, button={'cn': (497, 914, 526, 928)}, file={'cn': './assets/cn/liberation/COMPLETED_2.png'})
COMPLETED_3 = Button(area={'cn': (497, 991, 527, 1007)}, color={'cn': (27, 96, 129)}, button={'cn': (497, 991, 527, 1007)}, file={'cn': './assets/cn/liberation/COMPLETED_3.png'})
COMPLETED_4 = Button(area={'cn': (363, 961, 398, 977)}, color={'cn': (163, 47, 174)}, button={'cn': (363, 961, 398, 977)}, file={'cn': './assets/cn/liberation/COMPLETED_4.png'})
COMPLETED_5 = Button(area={'cn': (361, 1039, 397, 1055)}, color={'cn': (60, 123, 167)}, button={'cn': (361, 1039, 397, 1055)}, file={'cn': './assets/cn/liberation/COMPLETED_5.png'})
COMPLETED_6 = Button(area={'cn': (363, 1115, 395, 1134)}, color={'cn': (196, 128, 44)}, button={'cn': (363, 1115, 395, 1134)}, file={'cn': './assets/cn/liberation/COMPLETED_6.png'})
