from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ADVANCED_MATERIALS = Button(area={'cn': (204, 607, 269, 672)}, color={'cn': (102, 97, 99)}, button={'cn': (204, 607, 269, 672)}, file={'cn': './assets/cn/daily/ADVANCED_MATERIALS.png'})
COMPLETED_CHECK = Button(area={'cn': (170, 204, 190, 223)}, color={'cn': (116, 111, 140)}, button={'cn': (170, 204, 190, 223)}, file={'cn': './assets/cn/daily/COMPLETED_CHECK.png'})
ENHANCE = Button(area={'cn': (366, 903, 413, 925)}, color={'cn': (26, 110, 155)}, button={'cn': (366, 903, 413, 925)}, file={'cn': './assets/cn/daily/ENHANCE.png'})
ENHANCEMENT_CHECK = Button(area={'cn': (341, 164, 437, 189)}, color={'cn': (137, 188, 244)}, button={'cn': (341, 164, 437, 189)}, file={'cn': './assets/cn/daily/ENHANCEMENT_CHECK.png'})
ENHANCE_CONFIRM = Button(area={'cn': (492, 1065, 550, 1094)}, color={'cn': (77, 199, 255)}, button={'cn': (492, 1065, 550, 1094)}, file={'cn': './assets/cn/daily/ENHANCE_CONFIRM.png'})
GOTO_EQUIPMENT_LIST = Button(area={'cn': (373, 199, 429, 217)}, color={'cn': (152, 153, 155)}, button={'cn': (373, 199, 429, 217)}, file={'cn': './assets/cn/daily/GOTO_EQUIPMENT_LIST.png'})
LU_CHECK = Button(area={'cn': (280, 841, 455, 862)}, color={'cn': (24, 53, 49)}, button={'cn': (280, 841, 455, 862)}, file={'cn': './assets/cn/daily/LU_CHECK.png'})
NORMAL_MATERIALS = Button(area={'cn': (98, 607, 152, 669)}, color={'cn': (113, 108, 109)}, button={'cn': (98, 607, 152, 669)}, file={'cn': './assets/cn/daily/NORMAL_MATERIALS.png'})
NO_ITEMS = Button(area={'cn': (338, 711, 454, 732)}, color={'cn': (188, 186, 186)}, button={'cn': (338, 711, 454, 732)}, file={'cn': './assets/cn/daily/NO_ITEMS.png'})
RANDOM_EQUIPMENT = Button(area={'cn': (110, 343, 136, 352)}, color={'cn': (175, 175, 176)}, button={'cn': (110, 343, 136, 352)}, file={'cn': './assets/cn/daily/RANDOM_EQUIPMENT.png'})
RECEIVE = Button(area={'cn': (533, 1142, 617, 1161)}, color={'cn': (149, 222, 255)}, button={'cn': (533, 1142, 617, 1161)}, file={'cn': './assets/cn/daily/RECEIVE.png'})
SW = Button(area={'cn': (289, 1156, 444, 1268)}, color={'cn': (117, 138, 152)}, button={'cn': (289, 1156, 444, 1268)}, file={'cn': './assets/cn/daily/SW.png'})
