from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

COMPLETED_CHECK = Button(area={'cn': (170, 204, 190, 223)}, color={'cn': (116, 111, 140)}, button={'cn': (170, 204, 190, 223)}, file={'cn': './assets/cn/daily/COMPLETED_CHECK.png'})
RECEIVE = Button(area={'cn': (533, 1142, 617, 1161)}, color={'cn': (149, 222, 255)}, button={'cn': (533, 1142, 617, 1161)}, file={'cn': './assets/cn/daily/RECEIVE.png'})
