from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

EMPTY_FORMATION = Button(area={'cn': (23, 910, 704, 1054)}, color={'cn': (221, 220, 219)}, button={'cn': (23, 910, 704, 1054)}, file={'cn': './assets/cn/event/EMPTY_FORMATION.png'})
HARD_AVAILABLE_CHECK = Button(area={'cn': (282, 732, 438, 754)}, color={'cn': (153, 156, 156)}, button={'cn': (282, 732, 438, 754)}, file={'cn': './assets/cn/event/HARD_AVAILABLE_CHECK.png'})
