from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

DAILY = Button(area={'cn': (182, 356, 217, 375)}, color={'cn': (199, 199, 206)}, button={'cn': (182, 356, 217, 375)}, file={'cn': './assets/cn/gift/DAILY.png'})
DAILY_CHECK = Button(area={'cn': (181, 356, 218, 375)}, color={'cn': (107, 221, 250)}, button={'cn': (181, 356, 218, 375)}, file={'cn': './assets/cn/gift/DAILY_CHECK.png'})
FAILED_CHECK = Button(area={'cn': (198, 547, 508, 568)}, color={'cn': (174, 174, 174)}, button={'cn': (198, 547, 508, 568)}, file={'cn': './assets/cn/gift/FAILED_CHECK.png'})
GENERAL_GIFT_CHECK = Button(area={'cn': (323, 111, 446, 141)}, color={'cn': (179, 185, 202)}, button={'cn': (323, 111, 446, 141)}, file={'cn': './assets/cn/gift/GENERAL_GIFT_CHECK.png'})
GIFT = Button(area={'cn': (111, 794, 164, 820)}, color={'cn': (109, 113, 117)}, button={'cn': (111, 794, 164, 820)}, file={'cn': './assets/cn/gift/GIFT.png'})
GOTO_GENERAL_GIFT = Button(area={'cn': (132, 261, 173, 306)}, color={'cn': (114, 115, 118)}, button={'cn': (132, 261, 173, 306)}, file={'cn': './assets/cn/gift/GOTO_GENERAL_GIFT.png'})
MONTHLY = Button(area={'cn': (579, 356, 615, 375)}, color={'cn': (199, 198, 207)}, button={'cn': (579, 356, 615, 375)}, file={'cn': './assets/cn/gift/MONTHLY.png'})
MONTHLY_CHECK = Button(area={'cn': (579, 356, 615, 374)}, color={'cn': (114, 224, 250)}, button={'cn': (579, 356, 615, 374)}, file={'cn': './assets/cn/gift/MONTHLY_CHECK.png'})
WEEKLY = Button(area={'cn': (379, 355, 417, 375)}, color={'cn': (198, 198, 206)}, button={'cn': (379, 355, 417, 375)}, file={'cn': './assets/cn/gift/WEEKLY.png'})
WEEKLY_CHECK = Button(area={'cn': (380, 356, 417, 375)}, color={'cn': (116, 224, 251)}, button={'cn': (380, 356, 417, 375)}, file={'cn': './assets/cn/gift/WEEKLY_CHECK.png'})
