import datetime

# This file was automatically generated by module/config/config_updater.py.
# Don't modify it manually.


class GeneratedConfig:
    """
    Auto generated configuration
    """

    # Group `Scheduler`
    Scheduler_Enable = False
    Scheduler_NextRun = datetime.datetime(1989, 12, 27, 0, 0)
    Scheduler_Command = 'NKAS'
    Scheduler_SuccessInterval = 0
    Scheduler_FailureInterval = 120
    Scheduler_ServerUpdate = '04:00'

    # Group `Emulator`
    Emulator_Serial = 'auto'
    Emulator_PackageName = 'com_proximabeta_nikke'  # com_proximabeta_nikke, com_gamamobi_nikke
    Emulator_ScreenshotMethod = 'DroidCast'  # DroidCast
    Emulator_ControlMethod = 'minitouch'  # minitouch
    Emulator_AdbRestart = False

    # Group `Reward`
    Reward_CollectSocialPoint = True
    Reward_CollectSpecialArenaPoint = True

    # Group `Storage`
    Storage_Storage = {}
