from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

COMPLETED_CHECK = Button(area={'cn': (659, 389, 673, 412)}, color={'cn': (239, 222, 220)}, button={'cn': (659, 389, 673, 412)}, file={'cn': './assets/cn/mission_pass/COMPLETED_CHECK.png'})
RANK_UP_CHECK = Button(area={'cn': (289, 586, 430, 619)}, color={'cn': (81, 84, 81)}, button={'cn': (289, 586, 430, 619)}, file={'cn': './assets/cn/mission_pass/RANK_UP_CHECK.png'})
RECEIVE = Button(area={'cn': (319, 1184, 402, 1203)}, color={'cn': (154, 222, 251)}, button={'cn': (319, 1184, 402, 1203)}, file={'cn': './assets/cn/mission_pass/RECEIVE.png'})
