from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

RECEIVE = Button(area={'cn': (497, 1074, 592, 1096)}, color={'cn': (137, 216, 251)}, button={'cn': (497, 1074, 592, 1096)}, file={'cn': './assets/cn/mailbox/RECEIVE.png'})
